name: conduit_codable
version: 3.2.1
homepage: https://github.com/conduit-dart/conduit-codable
description: A serialization library for converting dynamic, structured data (JSON, YAML) into Dart types.
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  meta: ^1.3.0
dev_dependencies:
  lint: ^1.0.0
  test: ^1.16.5
