name: application
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  dependency:
    git:
      url: https://github.com/kbaylosis/conduit.git
      ref: fix/attach-finalizer-on-connect_fork
      path: packages/dependency
  meta: ^1.3.0

dev_dependencies:
  lint: ^2.0.0
  test: ^1.21.6
