name: conduit_common
version: 4.2.0
description: Common classes shared by conduit projects.
repository: https://github.com/bsutton/conduit-orm
publish_to: none

environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  conduit_open_api: #^4.2.0
    git: 
      url: https://github.com/kbaylosis/conduit.git
      ref: fix/attach-finalizer-on-connect_fork
      path: packages/open_api
dev_dependencies:
  lint: ^2.0.0
