name: dependency
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  conduit_runtime:
    git:
      url: git@github.com:kbaylosis/conduit.git
      ref: fix/attach-finalizer-on-connect_fork
      path: packages/runtime

dev_dependencies:
  lint: ^2.0.0
  test: ^1.21.6
