name: conduit_runtime
version: 4.2.0
description: Provides behaviors and base types for packages that can use mirrors and be AOT compiled.
repository: https://github.com/conduit-dart/conduit-runtime
publish_to: none

environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  analyzer: ^5.1.0
  args: ^2.0.0
  conduit_isolate_exec: #^4.2.0
    git: 
      url: git@github.com:kbaylosis/conduit.git
      ref: fix/attach-finalizer-on-connect_fork
      path: packages/isolate_exe
  io: ^1.0.3
  package_config: ^2.1.0
  path: ^1.8.0
  pubspec: ^2.0.1
  yaml: ^3.1.0
dev_dependencies:
  fs_test_agent:
    path: ../fs_test_agent
  lint: ^2.0.0
  test: ^1.21.6
