name: conduit_test
version: 4.2.0
homepage: https://github.com/conduit-dart/conduit
description: Utilities for writing automated tests for Conduit applications
publish_to: none

environment:
  sdk: ">=2.18.6 <3.0.0"
dependencies:
  test: ^1.21.6
  matcher: ^0.12.12
  conduit_core:
    git: 
      url: git@github.com:kbaylosis/conduit.git
      ref: fix/attach-finalizer-on-connect_fork
      path: packages/core
dev_dependencies:
  conduit_common_test:
    git: 
      url: git@github.com:kbaylosis/conduit.git
      ref: fix/attach-finalizer-on-connect_fork
      path: packages/common_test
  test_core: ^0.4.18
