name: conduit_open_api
version: 4.2.0
homepage: https://github.com/conduit-dart/open-api-dart
description: Data structures for OpenAPI (Swagger) specification. Reads and writes JSON specifications.
publish_to: none

environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  conduit_codable: #^4.2.0
    git: 
      url: https://github.com/kbaylosis/conduit.git
      ref: fix/attach-finalizer-on-connect_fork
      path: packages/codable
  meta: ^1.1.5
dev_dependencies:
  lint: ^2.0.0
  test: ^1.3.0
